### ISSUE TITLE
Odd behaviour concerning the Spam Filter

### ISSUE THREAD

**Issue by Myldero** [CraftyMyner/MynePanel#42]
When looking at the logs, I found this:
`/tellraw §2 ["",{"text":"[ChatFilter]: ","color":"light_purple"},{"text":"Please watch the: ","color":"blue"},{"text":"Spam","color":"light_purple"}]`
I have no idea why it does this and I haven't checked if this happens every time someone spams or if it was just random.

**Comment by CraftyMyner** [comment]
Do you have pre or post fixes? If so, can you give me a sample of what the look like. Better yet, could  you give me a line of spam that the chat filter was supposed catch?

Thanks,
Crafty

**Comment by Myldero** [comment]
I found out that it's because I use prefixes to show ranks. Like "§4[Owner] §c" would turn up as `/tellraw §4 Message` This also occurs with the old chat filter. This might've occured because I accidentally ran CMPanel instead of MynePanel. That was a long time ago though and this bug did not occur right after I did that.

**Comment by CraftyMyner** [comment]
Adjusted Spam filter regex, fixed!
