### ISSUE TITLE
Players can kick others using the chat filter

### ISSUE THREAD

**Issue by Myldero** [CraftyMyner/MynePanel#52]
I'm getting reports of players making silly messages like this: 

----------------------------------- <Pixel_Narwhal> lol

to make the chat filter think that another player is spamming.
This can be used to effectively kick or ban other players with the chat filter.

**Comment by CraftyMyner** [comment]
I am quite surprised that this actually works, usually it only tricks people ingame. I made a small adjustment to the regex and it looks like it's working correctly in the next release.
