### ISSUE TITLE
Logging of Mynepanel user actions

### ISSUE THREAD

**Issue by blockbandit** [CraftyMyner/MynePanel#61]
It is necessary to have MynePanel user actions, such as kick and ban be logged for accountability. 
Proposed Format

TIMESTAMP: 
USER: MynePanel username
ACTION: KICK/BAN
TARGET: playername kicked or banned
REASON:

**Comment by CraftyMyner** [comment]
New logger should include an auth.log with all successful and failed logins, as well as actions.log with all file manager and kick/ban actions.
