### ISSUE TITLE
Add {site} to votifier extension

### ISSUE THREAD

**Issue by blockbandit** [CraftyMyner/MynePanel#67]
For Minecraft servers which are listed on multiple votifier-aware server directory sites, it is desirable have the possibility to mention the site on which the player has voted 
e.g.
Thank you {player} for having voted on {site}

would give
BlockBandit voted on MCSL

**Comment by CraftyMyner** [comment]
There are 3 options, {site} {service} or {sender} what one would you like added?

**Comment by CraftyMyner** [comment]
{Service} will be used.

**Comment by CraftyMyner** [comment]
Added 1.2.45-702
