### ISSUE TITLE
Chatfilter immunity for MynePanel users

### ISSUE THREAD

**Issue by blockbandit** [CraftyMyner/MynePanel#72]
It is desirable to have an option where MynePanel users can be given immunity and/or higher tolerance from ChatFilter settings if their Minecraft name matches their MynePanel login name. One of the purposes for multi-user is to have Moderators/Helpers with the ability to only kick and ban players. Often these server staff need to give HTTP links in chat, which would cause them to be kicked.

**Comment by CraftyMyner** [comment]
Will be added to user options menu, can be manually added to chat filter whitelist as of now.
